### ISSUE TITLE
PAUL?

### ISSUE THREAD

**Issue by ghost** [Gira-X/koala-upb-scraper.py#1]
Did you ever try something similar for PAUL? I tried modifying your code to log into PAUL instead of koaLA, but PAUL's login page is a bit weird, I couldn't find the csrf_token

**Comment by Dima-369** [comment]
I didn't try anything similar because it has been already done in a nice web interface :)

Check this out: https://paula-upb.de/

**Comment by ghost** [comment]
Looks pretty cool, but it doesn't actually let you log in to your account, does it?

**Comment by Dima-369** [comment]
Yeah, you can't login and have to transfer your lectures manually each term.

---

And PAUL doesn't use CSRF.
From glancing at the network requests, it seems to store the login data in the query parameters which is such a bad login solution.

Besides, do you want me to provide a tiny Python script which shows how to login into PAUL?

**Comment by ghost** [comment]
That would be awesome! I've never really done that much network stuff before. 
And yeah Paul kinda sucks, always takes so many clicks to get where I want. And don't get me started on those ugly long URLs...

**Comment by Dima-369** [comment]
Well, the URLs have to be that long because the login information is stored there.
If you get your hands on someone's browser URL after he is logged in, you can do everything as if you were logged in. No password required :)

---

And I created a repository for the login script: https://github.com/Gira-X/paul-login.py

If you have further questions, create an issue in that repository.
